name: CI

on: [workflow_call, workflow_dispatch]

env:
  MAIN_REPOSITORY_ORIGIN: 'u-ways/software-engineering-workexperience'

jobs:
  Test-Runner:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          cache: gradle
      - name: "Setting Challenge Solution Checker Context"
        # This is used to trigger inverse matching conditions on the unsolved (main) repository
        # NOTE: The reason why this is defined here instead of the env context because the environment
        #       variables cannot be defined in terms of other variables.
        #       See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
        run: echo "INVERSE_MATCHER=${{ github.repository == env.MAIN_REPOSITORY_ORIGIN && 'true' || 'false' }}" >> $GITHUB_ENV
      - name: 'Checking Challenge Number 1 Solution'
        run: ./gradlew -DinverseMatcher=${{ env.INVERSE_MATCHER }} test --tests "io.github.u.ways.Challenge1Test" --info
      - name: 'Checking Challenge Number 2 Solution'
        run: ./gradlew -DinverseMatcher=${{ env.INVERSE_MATCHER }} test --tests "io.github.u.ways.Challenge2Test" --info
      - name: 'Checking Challenge Number 3 Solution'
        run: ./gradlew -DinverseMatcher=${{ env.INVERSE_MATCHER }} test --tests "io.github.u.ways.Challenge3Test" --info
      - name: 'Checking Challenge Number 4 Solution'
        run: ./gradlew -DinverseMatcher=${{ env.INVERSE_MATCHER }} test --tests "io.github.u.ways.Challenge4Test" --info
      - name: 'Checking Challenge Number 5 Solution'
        run: ./gradlew -DinverseMatcher=${{ env.INVERSE_MATCHER }} test --tests "io.github.u.ways.Challenge5Test" --info
      - name: 'Uploading test artifacts'
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./build/test-results/test/*.xml
            ./build/reports

  Test-Reporter:
    needs: Test-Runner
    if: success() || failure()
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Downloading all artifacts'
        uses: actions/download-artifact@v3
      - name: 'Generating test report for Github actions'
        uses: dorny/test-reporter@v1.6.0
        with:
          name: 'Test Report: JUnit'
          path: ./test-artifacts/test-results/test/*.xml
          fail-on-error: 'false'
          reporter: java-junit