name: CICD

on:
  push:
    branches:
      - '*'
    paths:
      - '*'
  pull_request:
    types: [ opened, synchronize, edited ]

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    # This only works for organization and repository secrets
    # See: https://github.com/actions/runner/issues/1413#issuecomment-1230408270
    secrets: inherit
